tasks:
  - name: open browser
    command: |
            mkdir -p gpinstall
            echo exit | docker run -v $PWD/gpinstall:/workspace -u $(id -u) -i gcr.io/gitpod-io/self-hosted/installer:latest bash
            mkdir -p ./db-init
            cp gpinstall/gitpod/helm/gitpod/config/db/init/*.sql ./db-init/
            rm -Rf gpinstall
            helm upgrade --install -f .gitpod.yml gitpod gitpod.io/gitpod --version=0.10.0
image:
  file: .gitpod.Dockerfile

ports:
  - port: 8080
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
    db:
        host: db
        port: 3306
        password: test

    # Disable built-in MySQL instance
    mysql:
      enabled: false

vscode:
  extensions:
    - felixfbecker.php-debug
    - cweijan.vscode-mysql-client2


